// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/rpc/code.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "google/rpc/Code.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CodeRoot

@implementation CodeRoot

@end

#pragma mark - Enum Code

GPBEnumDescriptor *Code_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Ok\000Cancelled\000Unknown\000InvalidArgument\000Dea"
        "dlineExceeded\000NotFound\000AlreadyExists\000Per"
        "missionDenied\000Unauthenticated\000ResourceEx"
        "hausted\000FailedPrecondition\000Aborted\000OutOf"
        "Range\000Unimplemented\000Internal\000Unavailable"
        "\000DataLoss\000";
    static const int32_t values[] = {
        Code_Ok,
        Code_Cancelled,
        Code_Unknown,
        Code_InvalidArgument,
        Code_DeadlineExceeded,
        Code_NotFound,
        Code_AlreadyExists,
        Code_PermissionDenied,
        Code_Unauthenticated,
        Code_ResourceExhausted,
        Code_FailedPrecondition,
        Code_Aborted,
        Code_OutOfRange,
        Code_Unimplemented,
        Code_Internal,
        Code_Unavailable,
        Code_DataLoss,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(Code)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:Code_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL Code_IsValidValue(int32_t value__) {
  switch (value__) {
    case Code_Ok:
    case Code_Cancelled:
    case Code_Unknown:
    case Code_InvalidArgument:
    case Code_DeadlineExceeded:
    case Code_NotFound:
    case Code_AlreadyExists:
    case Code_PermissionDenied:
    case Code_Unauthenticated:
    case Code_ResourceExhausted:
    case Code_FailedPrecondition:
    case Code_Aborted:
    case Code_OutOfRange:
    case Code_Unimplemented:
    case Code_Internal:
    case Code_Unavailable:
    case Code_DataLoss:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
